# Generated by Django 4.2.14 on 2024-10-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('background_image', models.ImageField(upload_to='lessons/backgrounds/')),
                ('content', models.TextField()),
            ],
        ),
    ]
