# Generated by Django 4.2.14 on 2024-10-28 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapp', '0003_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'الدروس'},
        ),
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name': 'درجة', 'verbose_name_plural': 'الدرجات'},
        ),
        migrations.AlterModelOptions(
            name='multiplechoiceanswer',
            options={'verbose_name': 'إجابة اختيار متعدد', 'verbose_name_plural': 'إجابات الاختيار المتعدد'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'اختبار', 'verbose_name_plural': 'الاختبارات'},
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'verbose_name': 'تقديم اختبار', 'verbose_name_plural': 'تقديمات الاختبارات'},
        ),
        migrations.AlterModelOptions(
            name='shortessayanswer',
            options={'verbose_name': 'إجابة سؤال مقالي', 'verbose_name_plural': 'إجابات الأسئلة المقالية'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'الملف الشخصي للمستخدم', 'verbose_name_plural': 'ملفات المستخدمين الشخصية'},
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='صورة اختيارية'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط اختياري'),
        ),
        migrations.AddField(
            model_name='shortessayquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='صورة اختيارية'),
        ),
        migrations.AddField(
            model_name='shortessayquestion',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط اختياري'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='background_image',
            field=models.ImageField(upload_to='lessons/backgrounds/', verbose_name='صورة الخلفية'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الدرس'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='graded_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التصحيح'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_by', to=settings.AUTH_USER_MODEL, verbose_name='المصحح'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='quizapp.quizsubmission', verbose_name='تقديم الاختبار'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_marks',
            field=models.FloatField(default=0.0, verbose_name='الدرجات الكلية'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.multiplechoicequestion', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='selected_choice',
            field=models.PositiveSmallIntegerField(choices=[(1, 'الخيار 1'), (2, 'الخيار 2'), (3, 'الخيار 3')], verbose_name='الخيار المحدد'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_answers', to='quizapp.quizsubmission', verbose_name='تقديم الاختبار'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='choice_1',
            field=models.CharField(max_length=255, verbose_name='الخيار 1'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='choice_2',
            field=models.CharField(max_length=255, verbose_name='الخيار 2'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='choice_3',
            field=models.CharField(max_length=255, verbose_name='الخيار 3'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_choice',
            field=models.PositiveSmallIntegerField(choices=[(1, 'الخيار 1'), (2, 'الخيار 2'), (3, 'الخيار 3')], verbose_name='الخيار الصحيح'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_text',
            field=models.TextField(verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_questions', to='quizapp.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان الاختبار'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='total_score',
            field=models.FloatField(default=0.0, verbose_name='الدرجة الكلية'),
        ),
        migrations.AlterField(
            model_name='shortessayanswer',
            name='answer_text',
            field=models.TextField(verbose_name='نص الإجابة'),
        ),
        migrations.AlterField(
            model_name='shortessayanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.shortessayquestion', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='shortessayanswer',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='shortessayanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_answers', to='quizapp.quizsubmission', verbose_name='تقديم الاختبار'),
        ),
        migrations.AlterField(
            model_name='shortessayquestion',
            name='question_text',
            field=models.TextField(verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='shortessayquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_questions', to='quizapp.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'معلم'), ('student', 'طالب')], max_length=10, verbose_name='نوع المستخدم'),
        ),
    ]
