# Generated by Django 4.2.14 on 2025-01-06 15:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_lesson_options_alter_marks_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفيديو')),
                ('youtube_id', models.CharField(max_length=10000, verbose_name='معرف فيديو يوتيوب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الفيديو')),
            ],
            options={
                'verbose_name': 'فيديو',
                'verbose_name_plural': 'فيديوهات',
            },
        ),
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={'verbose_name': 'سؤال اختيار متعدد', 'verbose_name_plural': 'أسئلة الاختيار المتعدد'},
        ),
        migrations.AlterModelOptions(
            name='shortessayquestion',
            options={'verbose_name': 'سؤال مقالي', 'verbose_name_plural': 'أسئلة مقالية'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الاختبار'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/backgrounds/', verbose_name='صورة الخلفية'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=tinymce.models.HTMLField(null=True, verbose_name='المحتوى'),
        ),
    ]
